version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
